### ISSUE TITLE
The reconstruction of the human arm

### ISSUE THREAD

**Issue by Xianjin111** [facebookresearch/pifuhd#110]
Hi!
Thanks for your perfect work. When I test your work on a T-pose, the result of human arm is not accurate as shown in fig1. Could you please tell me what can I do to improve the result? I only want to get a complete 3D model for this T-pose person.
![企业微信截图_16127725391480](https://user-images.githubusercontent.com/46471572/107195810-cd46b300-6a2c-11eb-8e9b-43a78c22421d.png)
![企业微信截图_16127725571397](https://user-images.githubusercontent.com/46471572/107195832-d172d080-6a2c-11eb-9d61-d9666a3e9645.png)

Thank you very much.

**Comment by cansik** [comment]
The problem is the T-Pose itself, as far as I know the training data used a lot of people in normal positions and not t-poses. As soon as you move his arms into a normal position, the recognition is fine:

![result_tpose_512](https://user-images.githubusercontent.com/5220162/107643205-22293a00-6c76-11eb-98e7-109bd97b7817.png)

![image](https://user-images.githubusercontent.com/5220162/107643301-3f5e0880-6c76-11eb-8867-339a30b86c12.png)

**Comment by Xianjin111** [comment]
> The problem is the T-Pose itself, as far as I know the training data used a lot of people in normal positions and not t-poses. As soon as you move his arms into a normal position, the recognition is fine:
> 
> ![result_tpose_512](https://user-images.githubusercontent.com/5220162/107643205-22293a00-6c76-11eb-98e7-109bd97b7817.png)
> 
> ![image](https://user-images.githubusercontent.com/5220162/107643301-3f5e0880-6c76-11eb-8867-339a30b86c12.png)

Thanks for the explanation! Very clear for me.
