### ISSUE TITLE
Render for BUFF dataset

### ISSUE THREAD

**Issue by kyleleey** [facebookresearch/pifuhd#46]
Hi, Because in the paper PIFuHD and the paper PIFu before, there are quantitative results on BUFF dataset, so did you train a new model on BUFF dataset for that evaluation? 
I want to know if you can share the render code for BUFF dataset's ply file? Because even the evaluation on BUFF requires the projection image of the 3D model.

**Comment by shunsukesaito** [comment]
We used BUFF only for evaluation, meaning we don't train a model using BUFF dataset. 

https://github.com/shunsukesaito/PIFu#data-generation-linux-only
The rendering is based on this pipeline but instead of adding shading, we simply take the color of ply files as it is since the shading is already baked in. We render them from yaw angles of 0, 90, 180, 270 degrees. You can look at evaluator.py as reference for evaluation.
https://github.com/facebookresearch/pifuhd/blob/master/lib/evaluator.py
