### ISSUE TITLE
Pixellation

### ISSUE THREAD

**Issue by sxyu** [facebookresearch/pifuhd#48]
PIFuHD's output seems to always be incredibly pixelated:
![image](https://user-images.githubusercontent.com/16251946/89619879-9c01e600-d843-11ea-8e9a-e208af070ec8.png)
Is this caused by the marching cubes sampling?

**Comment by shunsukesaito** [comment]
I figured this pixelation was mainly caused by the inconsistent use of align_corners in multiple places at the time of training (the default behaviour of F.interpolate and F.grid_sample changed at some point. Although the current code base as well as PIFu repository already fixed this, the issue remains in the pretrained model.)

**Comment by sxyu** [comment]
I see
